CREATE TABLE IF NOT EXISTS film (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    releaseDate DATE,
    duration BIGINT,
    mpa_id INTEGER,
    likes INTEGER
);
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255),
    login VARCHAR(255),
    email VARCHAR(255),
    birthday DATE
);
CREATE TABLE IF NOT EXISTS friends (
    user_id BIGINT NOT NULL REFERENCES users(id),
    friend_id BIGINT NOT NULL REFERENCES users(id),
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (user_id, friend_id)
);
CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY,
    name VARCHAR(40) NOT NULL
);
CREATE TABLE IF NOT EXISTS MPA (
    id INTEGER PRIMARY KEY,
    name VARCHAR(8) NOT NULL,
    description VARCHAR(80)
);
CREATE TABLE IF NOT EXISTS films_genres (
    film_id INTEGER NOT NULL REFERENCES film(id),
    genre_id INTEGER NOT NULL REFERENCES genres(id),
    PRIMARY KEY (film_id, genre_id)
);
CREATE TABLE IF NOT EXISTS likes (
    user_id INTEGER NOT NULL REFERENCES users(id),
    film_id INTEGER NOT NULL REFERENCES film(id),
    PRIMARY KEY (user_id, film_id)
);